sudo: false

language: node_js

node_js:
    - '10'

branches:
    only:
        - master
        - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
    directories:
        - node_modules

# Set DISPLAY for Xvfb
env:
    - DISPLAY=:99.0

# Use APT Addon to install Chrome
addons:
    apt:
        sources:
            - google-chrome
        packages:
            - google-chrome-stable

before_install:
    - xvfb

install:
    - npm install
    - npm install coveralls

script:
    - npm lint
    - npm test
    - cat ./coverage/reactions/lcov.info | ./node_modules/coveralls/bin/coveralls.js
